### ISSUE TITLE
Recent issue with v3 Github Action

### ISSUE THREAD

**Issue by osamahamad** [awslabs/automated-security-helper#154]
![Image](https://github.com/user-attachments/assets/5231c1ea-b1f2-41ec-af77-a0e73a80a8ea)

I'm using 

```
name: Run ASH
on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
env:
  PYTHON_VERSION: "3.12"
jobs:
  ash:
    uses: awslabs/automated-security-helper/.github/workflows/run-ash-security-scan.yml@v3.0.0-beta-20250526151056
    # uses: ./.github/workflows/run-ash-security-scan.yml
    permissions:
      #checkov:skip=CKV2_GHA_1:The permissions are not set to write-all at the top-level, or any level
      contents: read # Required to read the repository contents in order to scan them with ASH
      checks: write # Required for writing CI check runs
      pull-requests: write # Required for writing comments with scan results to pull requests
      security-events: write # Required for collection of SARIF code scanning results for GitHub Advanced Security checks
    with:
      ash-version: ${{ github.head_ref || github.ref_name }}
      repository-owner: ${{ github.repository_owner }}
      ash-args: '--inspect'
      fail-on-findings: false
      collect-junit-xml-report: true
      collect-sarif-report: true
      post-pr-comment: true
      verbose: true
      python-version: '3.12'
      ash-mode: container
      output-dir: '.ash/ash_output'
      config: '.ash/.ash.yaml'

```

Tried different tags, also tried the old workflow with two inputs --       post-pr-comment: true and       fail-on-findings: false only. 

All fails.

**Comment by scrthq** [comment]
Hey @osamahamad - Could you please try with the following adjustments (shift of tag to `v3.0.0-beta`, remove `with` section)? 

Please note that the arguments/`with` section in this repo's usage of the same workflow is customized for this repo, so some arguments may not be applicable such as `config`, `ash-args`, and `ash-version` using the repository ref as input.

```yaml
name: Run ASH
on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}
env:
  PYTHON_VERSION: "3.12"
permissions:
  
jobs:
  ash:
    uses: awslabs/automated-security-helper/.github/workflows/run-ash-security-scan.yml@v3.0.0-beta
    permissions:
      contents: read # Required to read the repository contents in order to scan them with ASH
      checks: write # Required for writing CI check runs
      pull-requests: write # Required for writing comments with scan results to pull requests
      security-events: write # Required for collection of SARIF code scanning results for GitHub Advanced Security checks
```

Thank you for trying out v3 and providing feedback!
